sudo: required
dist: trusty
addons:
  sonarqube:
    organization: garethahealy-github
    token:
      secure: R9LiobCnRzJ7XYtks/6JaYajE44Bmbpz/c04sSSLNPxuiAVI+J29JVe/BiBE3GpJLFDQthgbWcVD/NLC9FRGzAlc5b9eby1UYiSRO0O5FuzXtcU2iDAH0nZr6XBSargXHmb0qS0VU+7hj/OpV8nimhGHc4Irpar1FtqFUlj0Igwf6lkq8vYBN0g/HPD1cpdZFX1pJP12rgJfVO0AXXyyMU9zK/TACYIG+ot+XKtC6AoFoFlQo7ngCfZahCmHPkUc9Uz44tUHn0L5ki6slYjCWAOkDNYDGZ8eNhpjvRoat9ZdAEqgZGOrUh6n7kaXbOSyt2+4jUv/bc0mdG2Zt7WHmcOwpK/cR+LpVL6rNqaDcvZZCD1kE+hyCMvvPejw4PyrrnXnJn0LDzMqfOrhtzVCtby7AsMkEXIdCszvqc4ODVeQoUXHWIWJdPFvr9qBZGVgnMZHyM2k3n5Xl9eUWCa1dcp8kJfDmKFdDxrCepiw6XVQdA64kdTiecR8uRy+jSmLu6oqgZzXzgpqhogSNll4S1glfIeL9abDgkHw1ci18rlZ4WAUdEzVGuOOkk1bV5HQant4N7M3wV5lZ0AuabgI0m7WnNqvhbjLYhoLqjLnhE8YLpSsbewCeuXVRv7bScoKd/mPan0wyz+hrNBx9ag0BhUuRHjAHqMzMdXdVGTgYKg=
env:
  global:
  - secure: bN4d6ZwFeiHcdlGHzcqgY1YaapSZpEL8gDEfcxYBzEhith7swsqRgqn2nuxCQzJqcvdBJnqBF9FhoZDnyyASytaVrunazNaXjVtl5CPXv1VN+zsp/BLfMbD1VYObsW56SKG/vj0OJdu4o9Rg8izu5CzB9U/Gx/2wmHEWnSYzrBC7+OgwGTaI3L4l24cqTBtwujxxzdg/89Eyes5w8pVCjZKj2HaLbQ9OLaetimPhEC2m9qG841CVDmJwSLvMJDG4o5BVh7dkuM/awpkRSS71IuM+xfN1LPs/beDPFGlDZPL8OYTtrO2Ts8EnXOtWd4MjDBGksp5FXUTR9Uv6FYfb82KenItvULNcYQ3hjneejit/+aGp1bixD6YXMwBe/u44yXoJQ/Pc3i4bFwrfRL1ICvGYEtLjgGEg+qTvlnBH6QCdsVCjONVIjjYVS9cI0fT1ZJS7MwZeyOJtDk1sqmpcI7zpWmlDQxkrWrc4TCCvjX/yPE31UhKJKSValJq3uV3O0FhsglSZhcTxcBYo28gmjEl5on5E+Im892XOeqZTd5ITCeMh25ORV2iXHSbvk+/8CyyADsMT1aukQRRhlb5qtByQJxFv3ZvzHh47n8xqwLm9/hJazUw4KnfmtJ5/WQoo6we/n9HHBjV+kSYizWs5IZD/5T3k+CCG9Gi3Pwa2YUw=
  - secure: BODbeS86n2j1u11CS4G1iDXXs/HbsVKVLGOzcTAZCw4FwoRlBMDeOo85CwzFBu/juhu2q4SEU9fhhy4iDszJX/XycssBsKuPqAmXf2Kz1WV2viRf26mwCnKgPED0GesFy9tnUVkRcHJVJQOa4oPydHwv6sCi5O+DQ7WerfwFFEKb1hHlGOPJTHNu9ldrHJ/2UEu1zdt8f5LZ4wWO23nUuwH8VLsaSPbMhHJ9/EzKDWt4CQOULkbzNe/XACEVnedjWxDwWwuVf68AA7CFOIg/STc+AgMCGww0FlM7eizbWuFJHIBuHe21Yl/3sgEST05tLn8pnu8cOBEIilG1EcGC0pdRqxaoLiGS5N9KXOP0kM+brt3Yck0DdptKBLbIEBxLoVOFzOF3CsRp3bHwRZp0lpeolsKdMhMxAbgZGsttaQgZcaY1lL2aJNAgSUodpWbTGmGnO43PiZOGodMbDYLpgiVBStOqigFhDQvaulvtt3rnftzABykUCMzeuOuldTW3kWyKxd4VIFjnal1C7+Pub3aW43wmASd9HZaBRMN4TerflcrHx+dXlGdqwlP8/6zyJnkyzPKWLUXeTZy4L2wp7JLYE0wbA993EKOrcvTLgMIeRRJO2VygFKi2rL53foLPvwaJYpETt5XxPTFKlskHw1v2YGmoDw5asid/OG39FMo=
  - secure: UbKpEecdf6GEppdoTqZPgQ74Ga51XHjxH1Tqod18+avC+YHIV7FOc0AKzSun4R55azapmz8HrK9HwztgpWIDMIPYZ7p4FKc1FeaO9HioqUIVZR0DxAJMp+dCHw6dz2XUXDv0kCqAncRALQVlPU0Q5n1U5b4AlmUMIqSOpEgpcOJmzNqTj4Lss+YzSEjjKJXgWnU04VixP0Wo0YpQI3vPC7zaIzZMp4TBWMHbFXpk7z9B0XJHp+LxpAiK7E46fhMLDq8Fi3XCXzJXpI9VRcQM9Ykd+qcpD8Iuu6G421NQ9Qhy1DOyxEQBUmjUrBsyzXqaMg/w6abb17DA8mxdsvcTjSNSyftjcYue3/ovGkw6AiLpvkG8n6d5a2PfOLceLVplL5dz4ErJh8TFtiS0g2ODr6FDyY0TO8vWwz7LEzjtv58lrXdCechkDEqpYaV+I+iRl3aT2ny+Lm5T39EuU+Esgkp2DPwYQVWw6EdCbFI8K56VJLrmqOO7ZZOojdk+pB2/08fsi8wTdWd6Nt6BSryN9q0KDupe8thkJ59Q+VYXCK57qNuNd9nN3ww6cVAR0UoEfGNscZcRVmwobj7S+zmOFNvEmksBdLgkU3GJBHwfDFvmU2pXNxyUk8g4Hb7Pp9ZdChp3Ee4p13zTUMXGbkJBgQsPVOeTCV7T0JtO2ZiSfF4=
  - secure: qrNbGpqg7TFhe+yCzYilfjOCpSAjCk2lklr+/FNYY6kKZYYVTlLWDRmk9F5htKUrJVY/jLwBDEcLx3Q7f0om3KtWKzu+nN6scdQyiSmxFhKLo3fpmr+UeWT0HSx/4LfX5oMqS+TGqwYi2mbPQ7YjRrh9NkS59p+a1xMxci0sS69kihj5AwwgkE8//yMfXpBwgE3so/JuoNZkG32gvv+4gXxrrLSzqBS/4MVGptVJMFcvb4oKkj/2eLV4DD26tXTvOwk21iApucdInp20X5qbMUnSfrDBC3uokgrVi5lSfrHX64tbDo37Iys9H8iDJzOyav1X+1tYc3c3LnXvHTRbLj6IZtbzqqIXM3OdrG8mA5TTGqsQ34ZFuOhC+bPt/l+WirGmHj0COfYoHjunwcL04iGDKFT7lUUBM4oHGG69z8vf+pGds5gR+1nJUWcH+oYrjSzgpVBHFW1+DJiSVuXPeIuqK8T+eFBic9+iso+32X2adwhJGax/kzbhaXsbeU/zZas6ZJ3kKFZaEOz8tP/8NtVUdWYGT0MfL9GiW2h9s1h3+ChOmKIHayxznkpShWZ9yl+GmzsyBHRtoWj9F9crqD9c+Jjfx1wFY3qMvnUwZhlCVMtlp2LaSRoSv0NFumy3fCHWldEC32CIFsoaWdGeenCO2BIodgKULD7NLHziuWU=
language: java
jdk:
- oraclejdk8
before_install:
- bash .travis/deploy-codesigning.sh
install:
- bash .travis/update.sh
- export M2_HOME=/usr/share/maven3 && export PATH=${M2_HOME}/bin:${PATH} && export MAVEN_OPTS="-Xms2048m -Xmx2048m"
- java -version && javac -version && mvn -version -B
before_script:
- mvn dependency:resolve-plugins dependency:resolve -Prelease-ossrh -s configuration/settings.xml -B
script:
- mvn clean install -s configuration/settings.xml -B
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -s configuration/settings.xml -B
deploy:
  provider: script
  script: bash .travis/deploy.sh
  skip_cleanup: true
  on:
    tags: false
    all_branches: true
cache:
  directories:
  - $HOME/.m2
  - $HOME/.victims
  - $HOME/.sonar/cache
